### ISSUE TITLE
Sharing to instagram without showing action sheet controller

### ISSUE THREAD

**Issue by holgersindbaek** [mglagola/MGInstagram#5]
Is this still not possible? I know that Nike does it in their running app. How do they do it?

**Comment by holgersindbaek** [comment]
??

**Comment by mglagola** [comment]
@holgersindbaek Yes, [seems to still be the case](https://instagram.com/developer/mobile-sharing/iphone-hooks/).

**Comment by holgersindbaek** [comment]
How can I change that? Other apps can share without showing that pop up!-- All the bestHolger Sindbaek · UI/UX Designer & Web/iOS Programmer · HolgerSindbaek.comFounder of Uninkd · iOS Publishing for Content Creators · Uninkd.comOn Mon, Apr 6, 2015 at 09:00,  mglagola/MGInstagram <reply@reply.github.com> wrote:            @holgersindbaek Yes, seems to still be the case.

**Comment by holgersindbaek** [comment]
My mistake... seems like you're right. Only way to share to instagram is by showing that popup.
